'use client'
import './globals.css'
import {useState} from 'react'
import UserModal from '../components/Modal'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Floating from '../components/Floating'
import {Provider,useDispatch} from 'react-redux'
import {AppDispatch, store} from './store'
import {addUser} from './features/user/userSlice'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Navbar openModal={() => setIsModalOpen(true)} />
          <Floating/>
          {children}
          <UserModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
        </Provider>
      </body>
    </html>
  )
}
